spring.application.name=payment-system
server.port=9090

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/sepa
spring.datasource.username=postgres
spring.datasource.password=jijokikolilomimo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JDBC session config (required for Spring Session JDBC)
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

# AMQP (rabbitMQ)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
